-- Comentários
-- Comando para criar banco de dados 
-- CREATE DATABASE Escola;

-- apagar banco de dados
-- DROP DATABASE Escola;

-- apagar tabelas do banco
-- DROP TABLE CLIENTES;

-- ATIVAR BANCO DE DADOS
USE ESCOLA;
-- CRIAR TABELAS
CREATE TABLE CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR (14) NOT NULL UNIQUE,
ENDERECO VARCHAR(60) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL

);