-- PROJETO SMARTCOFFEE

CREATE DATABASE SMARTCOFFEE_ANNA;
CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR (14) NOT NULL UNIQUE,
NOME VARCHAR (60) NOT NULL,
TELEFONE VARCHAR (15) NOT NULL,
EMAIL VARCHAR (20) NOT NULL
);
CREATE TABLE IF NOT EXISTS PAGAMENTOS (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
VALOR_PAGO DECIMAL (5,2) DEFAULT 0.00,
CLIENTE VARCHAR (20) NOT NULL UNIQUE,
PEDIDO VARCHAR (30) NOT NULL UNIQUE,
FORMA_PAGAMENTO ENUM ('CREDITO', 'DEBITO', 'PIX', 'DINHEIRO') DEFAULT "PIX"
);
CREATE TABLE IF NOT EXISTS PRODUTOS (
ID_PRODUTOS INT AUTO_INCREMENT PRIMARY KEY,
CATEGORIA VARCHAR (20) NOT NULL,
QUANTIDADE INT NOT NULL,
PRECO INT NOT NULL,
NOME_PRODUTO DECIMAL(5,2) DEFAULT 0.00
);
CREATE TABLE IF NOT EXISTS ESTOQUE (
ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
QUANTIDADE_DISPONIVEL INT NOT NULL, 
DATA_VALIDADE INT NOT NULL,
UNIDADE INT NOT NULL,
PRODUTO VARCHAR (20) NOT NULL
);
SHOW TABLES;