-- COMANDO PARA CRIAR BD
CREATE DATABASE ACADEMIA_ANNA;
CREATE DATABASE IF NOT EXISTS ACADEMIA_ANNA;

-- 2 ATUALIZAR SCHEMAS
-- 3 COMANDO PARA ATIVAR bd
--   USE ACADEMIA_ANNA;

-- COMANDO PARA APAGAR TABELA
 DROP TABLE CLIENTES;
-- COMANDO PARA APAGAR BD
-- DROP DATABASE ACADEMIA_ADRYAN;

-- COMANDO CRIAR TABELA
CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR (14) NOT NULL UNIQUE,
NOME VARCHAR (60) NOT NULL,
TELEFONE VARCHAR (15) NOT NULL,
ENDERECO VARCHAR (100),
DATA_NASCIMENTO DATE NOT NULL,
STATUS_CLIENTES ENUM ('PENDENTE', 'ATIVO', 'INATIVO') DEFAULT "ATIVO",
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ALUNOS (
ID_ALUNOS INT AUTO_INCREMENT PRIMARY KEY,
SERIE VARCHAR (10) NOT NULL,
IDADE INT NOT NULL,
NOME VARCHAR (60) NOT NULL,
SALA VARCHAR (20) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL
);
create table planos (
id_planos int auto_increment primary key, 
nome_plano varchar (20) not null,
tipos_plano char(10) default "mensal",
valor decimal (5,2) default 0.00,
adicionais char(10) default "exame",
observacao text
);
-- COMANDOS PARA ALTERAR E CORRIGIR
-- ADICIONANDO UM CAMPO (ATRIBUTO) NOVO
ALTER TABLE CLIENTES ADD EMAIL VARCHAR(100);

-- MODIFICAR TIPO DE DADOS OU CAMPOS
ALTER TABLE CLIENTES MODIFY EMAIL VARCHAR(150);

-- RENOMEAR TABELAS
RENAME TABLE CLIENTES TO CLIENTESS;

-- EXCLUIR ATRIBUTO   
ALTER TABLE CLIENTESS DROP COLUMN EMAIL;

-- VISUALIZAR TABELAS NO BD
SHOW TABLES;

-- LIMPAR DADOS DA TABELA
TRUNCATE TABLE ALUNOS;
-- INSERIR DADOS NO BD
INSERT INTO clientes (ID_CLIENTE, NOME, CPF, TELEFONE, ENDERECO, DATA_NASCIMENTO, STATUS_CLIENTE, DATA_CADASTRO)
VALUES ('', 'ANNA', '123.456.789-78', '(19) 9 7894-4565', 'RUA SENAI', '13/13/2013', 'ATIVO','');

CREATE TABLE FUNCIONARIOS (
ID_FUNCIONARIO INT PRIMARY KEY,
EMAIL VARCHAR(255) UNIQUE
);

-- COMANDO PARA INSERIR DADOS
INSERT INTO FUNCIONARIOS (ID_FUNCIONARIO, EMAIL)
VALUES (1,'ANNA@SENAI.COM.BR');
INSERT INTO FUNCIONARIOS (ID_FUNCIONARIO, EMAIL)
VALUES (3,'BRUNO@SENAI.COM.BR');

-- COMANDO PARA CONSULTAR INFORMAÇÕES NA TABELA
SELECT * FROM FUNCIONARIOS;  